import { DocPage, Section, RelatedLinks } from '../../ui/DocPage';
import { DS_VERSION } from '../../lib/version';

/* ------------------------------------------------------------------ *
 * Releases foundation — hand-curated changelog rendered in brutalist
 * format. Source of truth lives in packages/{ds,tokens}/CHANGELOG.md
 * (auto-generated by changesets); this page summarizes the highlights
 * for humans. Update when a release ships.
 * ------------------------------------------------------------------ */

export const title = 'RELEASES';
export const slug = 'releases';

interface Release {
  version: string;
  date: string;
  status: 'shipped' | 'unreleased' | 'next';
  packages: string[];
  highlights: { title: string; body: string }[];
  why?: string;
}

const RELEASES: Release[] = [
  {
    version: '1.1.0',
    date: 'NEXT',
    status: 'next',
    packages: ['@touch-grass-ds/react'],
    why: 'Spacing tier overhaul + asChild slot. Visual-only refinement, public API unchanged.',
    highlights: [
      {
        title: 'SPACING TIER OVERHAUL',
        body: 'Every interactive primitive snapped to a 5-tier table on the 4/8/12/16/20/24/32 scale. Buttons get min-w-32 so short labels stop reading as squares. Tag drops to a 32px chip with a 1px border + invisible 48px hit area. Badge tightens to 16/24px so it never reads as a control. Input centers its caret with leading-none. Checkbox and Switch finally meet WCAG 2.5.5 via 48px label rows.',
      },
      {
        title: 'ASCHILD SLOT ON BUTTON & BADGE',
        body: 'Both components accept asChild via Radix Slot, so a styled <a> or <Link> can adopt the brutalist class set without wrapper hacks. Disabled translates to aria-disabled + pointer-events-none for non-button elements.',
      },
      {
        title: 'TIER CONTRACT PUBLISHED',
        body: 'New tiers table on the Spacing foundation page locks the 5-row contract. Future primitives must snap to one of those rows. Regression tests on Button/Input/Tag/Badge enforce min-h, min-w, padding, and border weight.',
      },
      {
        title: 'TOKEN DISCIPLINE',
        body: 'Removed the last hardcoded color in primitives (Checkbox stroke="black" → currentColor). Centralized DS version in docs-site/lib/version.ts, read from package.json — Nav badge and meta rows can never drift from the published version again.',
      },
    ],
  },
  {
    version: '1.0.1',
    date: 'NEXT',
    status: 'next',
    packages: ['@touch-grass-ds/tokens', '@touch-grass-ds/react'],
    highlights: [
      {
        title: '3-TIER TEXT HIERARCHY + HAIRLINE-STRONG',
        body: 'Replaced --color-muted with --color-fg-muted and --color-fg-subtle for 3-tier text hierarchy. Added --color-hairline-strong for emphasis borders. Regenerated Swift constants.',
      },
      {
        title: 'SWITCH PERCEPTIBILITY FIX',
        body: 'Checked thumb is now black-with-lime-border on a lime track instead of lime-on-lime. 9.1:1 contrast — the thumb is unmistakable in either position.',
      },
    ],
  },
  {
    version: '1.0.0',
    date: '2026-04-13',
    status: 'shipped',
    packages: ['@touch-grass-ds/tokens', '@touch-grass-ds/react'],
    why: 'First public release. Transition from private v0.0.x to a version third parties can install.',
    highlights: [
      {
        title: 'TOKENS — SIX COLORS, ELEVEN SPACING STEPS',
        body: 'bg, fg, earned, danger, hairline, bg-alt — all as CSS variables, Tailwind v4 theme, W3C Figma tokens, and auto-generated Swift constants via Style Dictionary. Spacing scale 0/4/8/12/16/20/24/32/48/64/96/128. Type scale Stat XL→Label. Border widths 1px hairline + 2px strong. Zero motion.',
      },
      {
        title: 'REACT — TEN PRIMITIVES, EIGHT PATTERNS',
        body: 'Button, Input, Badge, Card, Tag, Divider, Stat, Timer, Checkbox, Switch as primitives. LeaderboardRow, FocusTimerDisplay, BeRealStamp, PatternInterruptModal, SessionSummaryCard, Field, Sparkline, Toast as patterns. All forwardRef, token-only colors, 48px tap targets, hard-halo focus, dashed disabled, block-character loading.',
      },
      {
        title: 'BRUTAL LINT ENFORCED',
        body: 'Prebuild step rejects rounded corners, motion utilities, and raw hex codes in DS source. The discipline is now a build error, not a code-review conversation.',
      },
      {
        title: 'GENERATOR CLI',
        body: '`pnpm run generate <primitive|pattern> <Name>` scaffolds component + test + docs page from templates. Keeps the 6-file lockstep automatic.',
      },
    ],
  },
];

const STATUS_COLOR: Record<Release['status'], string> = {
  shipped: 'text-[var(--color-fg)]',
  unreleased: 'text-[var(--color-fg-muted)]',
  next: 'text-[var(--color-earned)]',
};

const STATUS_LABEL: Record<Release['status'], string> = {
  shipped: 'SHIPPED',
  unreleased: 'UNRELEASED',
  next: 'NEXT',
};

export function Releases() {
  return (
    <DocPage
      eyebrow="FOUNDATIONS / RELEASES"
      title="RELEASES"
      kicker="What shipped, when, why. Source of truth lives in CHANGELOG.md per package — this is the human-readable version."
      meta={{
        status: 'stable',
        version: DS_VERSION,
        role: 'changelog',
        importPath: 'CHANGELOG.md',
      }}
    >
      <Section eyebrow="SCHEDULE" title="HOW WE RELEASE">
        <div className="border border-[var(--color-hairline)]">
          {[
            ['CHANGESETS', 'Every PR with a user-visible change adds a .changeset/*.md file. The bot opens a Release PR that bundles them and bumps versions semver-style.'],
            ['MERGE → PUBLISH', 'Merging the Release PR triggers .github/workflows/release.yml which runs the build, regenerates CHANGELOG.md, and publishes to npm.'],
            ['NO MANUAL TAGS', 'You never run `npm publish` by hand. If a release doesn\'t go through changesets, it didn\'t happen.'],
            ['BREAKING = MAJOR', 'API removal or class output change → major bump. New props or new components → minor. Visual fix that doesn\'t change the API → patch (or minor if the visual is dramatic enough that consumers should know).'],
          ].map(([k, v], i, arr) => (
            <div
              key={k}
              className={`grid grid-cols-[120px_1fr] md:grid-cols-[200px_1fr] ${
                i < arr.length - 1 ? 'border-b border-[var(--color-hairline)]' : ''
              }`}
            >
              <div className="p-5 font-mono text-[12px] md:text-[13px] font-black uppercase tracking-[0.12em] text-[var(--color-earned)] border-r border-[var(--color-hairline)]">
                {k}
              </div>
              <div className="p-5 font-mono text-[13px] md:text-[14px] font-semibold text-[var(--color-fg)] leading-relaxed">
                {v}
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section eyebrow="HISTORY" title="EVERY VERSION">
        <ol className="space-y-12">
          {RELEASES.map((r) => (
            <li key={r.version} className="border border-[var(--color-hairline)]">
              {/* Header band */}
              <header className="grid grid-cols-1 md:grid-cols-[1fr_auto] border-b-2 border-[var(--color-fg)]">
                <div className="p-6 md:p-8 border-b md:border-b-0 md:border-r border-[var(--color-hairline)]">
                  <div className="font-mono text-[11px] font-black uppercase tracking-[0.14em] text-[var(--color-earned)] mb-3">
                    // VERSION
                  </div>
                  <div className="font-black text-[56px] md:text-[80px] leading-none tracking-[-0.04em] text-[var(--color-fg)]">
                    {r.version}
                  </div>
                  {r.why && (
                    <p className="mt-5 font-mono text-[14px] font-semibold text-[var(--color-fg)] max-w-[60ch] leading-relaxed">
                      {r.why}
                    </p>
                  )}
                </div>
                <div className="p-6 md:p-8 grid grid-cols-2 md:grid-cols-1 md:gap-6">
                  <div>
                    <div className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[var(--color-earned)] mb-2">
                      // STATUS
                    </div>
                    <div className={`font-mono text-[14px] font-black uppercase tracking-[0.04em] ${STATUS_COLOR[r.status]}`}>
                      {STATUS_LABEL[r.status]}
                    </div>
                  </div>
                  <div>
                    <div className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[var(--color-earned)] mb-2">
                      // DATE
                    </div>
                    <div className="font-mono text-[14px] font-black uppercase tracking-[0.04em] text-[var(--color-fg)]">
                      {r.date}
                    </div>
                  </div>
                </div>
              </header>

              {/* Packages */}
              <div className="px-6 md:px-8 py-4 border-b border-[var(--color-hairline)] bg-[var(--color-bg-alt)] flex flex-wrap gap-2">
                {r.packages.map((p) => (
                  <span
                    key={p}
                    className="inline-flex items-center px-3 py-1 font-mono text-[11px] font-black uppercase tracking-[0.1em] border border-[var(--color-earned)] text-[var(--color-earned)]"
                  >
                    {p}
                  </span>
                ))}
              </div>

              {/* Highlights */}
              <ol>
                {r.highlights.map((h, hi) => (
                  <li
                    key={h.title}
                    className={`grid grid-cols-1 md:grid-cols-[280px_1fr] ${
                      hi < r.highlights.length - 1 ? 'border-b border-[var(--color-hairline)]' : ''
                    }`}
                  >
                    <div className="p-6 md:p-8 border-b md:border-b-0 md:border-r border-[var(--color-hairline)]">
                      <div className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[var(--color-earned)] mb-2">
                        // {String(hi + 1).padStart(2, '0')}
                      </div>
                      <h3 className="font-mono text-[14px] md:text-[15px] font-black uppercase tracking-[0.06em] text-[var(--color-fg)] leading-tight">
                        {h.title}
                      </h3>
                    </div>
                    <p className="p-6 md:p-8 font-mono text-[13px] md:text-[14px] font-semibold text-[var(--color-fg)] leading-relaxed max-w-[68ch]">
                      {h.body}
                    </p>
                  </li>
                ))}
              </ol>
            </li>
          ))}
        </ol>
      </Section>

      <Section eyebrow="MACHINE-READABLE" title="RAW CHANGELOGS">
        <div className="grid grid-cols-1 md:grid-cols-2 border border-[var(--color-hairline)]">
          {[
            { label: '@TOUCH-GRASS-DS/REACT', href: 'https://github.com/thiagoxikota/touch-grass/blob/main/packages/ds/CHANGELOG.md' },
            { label: '@TOUCH-GRASS-DS/TOKENS', href: 'https://github.com/thiagoxikota/touch-grass/blob/main/packages/tokens/CHANGELOG.md' },
          ].map((c, i) => (
            <a
              key={c.href}
              href={c.href}
              target="_blank"
              rel="noreferrer noopener"
              className={`block p-6 md:p-8 ${i === 0 ? 'border-b md:border-b-0 md:border-r' : ''} border-[var(--color-hairline)] hover:bg-[var(--color-earned)] hover:text-[var(--color-bg)]`}
            >
              <div className="font-mono text-[10px] font-black uppercase tracking-[0.16em] text-[var(--color-earned)] mb-3">
                // PACKAGE
              </div>
              <div className="font-mono text-[16px] font-black uppercase tracking-[0.04em]">
                {c.label} ↗
              </div>
            </a>
          ))}
        </div>
      </Section>

      <RelatedLinks
        items={[
          { label: 'NPM · REACT', to: 'https://www.npmjs.com/package/@touch-grass-ds/react', kind: 'external' },
          { label: 'NPM · TOKENS', to: 'https://www.npmjs.com/package/@touch-grass-ds/tokens', kind: 'external' },
          { label: 'GITHUB RELEASES', to: 'https://github.com/thiagoxikota/touch-grass/releases', kind: 'external' },
        ]}
      />
    </DocPage>
  );
}
